### ISSUE TITLE
Error: Failed to upload part (403).

### ISSUE THREAD

**Issue by zacharytyhacz** [upload-js/upload-js#11]
## Version

```
+     "@bytescale/sdk": "^3.31.1",
```

I am attempting to upload a small png file with this snippet using TypeScript and Node.js version 20

```typescript
// upload.ts
import * as Bytescale from "@bytescale/sdk";
import * as fs from 'fs'
import nodeFetch from "node-fetch";

const uploadManager = new Bytescale.UploadManager({
  fetchApi: nodeFetch as any,
  apiKey: 'i have tried using my secret key and public key, both give same error'
});

export const uploadFileFromPath = async (filePath: string): Promise<string> => {
    const data = fs.readFileSync(filePath)
    console.log({ data }) // file does exist is and is a buffer. 

    try {
        const res = await uploadManager.upload({
            data,
            mime: 'image/png',
            originalFileName: filePath,
        })

        return res.fileUrl
    } catch (err) {
        console.error(err)
    }
}

const start = async () => {
    const fileUrl = await uploadFileFromPath('./1707182041670-10.png')
    console.log({ fileUrl })
}
start()

```
`node --loader ts-node/esm ./upload.ts`

I am getting the following error:
```
Error: Failed to upload part (403).
    at file:///Users/zact/Projects/scourz/application/node_modules/@bytescale/sdk/dist/node/esm/main.mjs:2222:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I cannot find any documentation about the errors, I am unsure if the `403` means that my API KEY or ACCESS is wrong but the error says 'failed to upload part' so maybe my request body is wrong?

**Comment by ljwagerfield** [comment]
Hi @zacharytyhacz 👋 

I wasn't able to reproduce the error using the code snippet you've kindly prepared.

We'll need to look into the logs; I see you've opened a support ticket, so let's continue over there, as our conversation may include account-specific details that wouldn't be appropriate to post here.

Talk soon!

**Comment by zacharytyhacz** [comment]
I fixed it - I had to create a NEW secret api key and use that. Not sure how the new one is different though

**Comment by ljwagerfield** [comment]
That's odd; have you revoked the old API key? If not, does it still fail on the old API key?
