### ISSUE TITLE
How can I cancel an upload

### ISSUE THREAD

**Issue by a1r93** [upload-js/upload-js#13]
Hello, I am trying to cancel uploads. From what I read in the documentation, I should be using `cancellationToken: { isCancelled: false }`, but I can't find a way to make this work.

The issue is that I am trying to pass a dynamic value to the isCancelled parameter, which is not being listened to. Here is an example of what I tried, which is not working.

```
let shouldBeCancelled = false;
setTimeout(() => {
    shouldBeCancelled = true;
}, 2000);

await uploadManager.upload({
    ...otherProperties,
    cancellationToken: {
        isCancelled: shouldBeCancelled,
    },
})
```

You can find the non working example in [this Codepen](https://codepen.io/a1r93/pen/zYQKdYB).

Is there maybe another way to trigger the cancel of an ongoing upload that I missed in the documentation?

Thanks for your help!

**Comment by ljwagerfield** [comment]
Hi @a1r93!

You'll need to set `isCancelled = true/false` directly on the object that declares the field -- having it reference a `let` that you're changing won't cause the `isCancelled` to update when you change the `let`.

For example, this works:

```
const example = {isCancelled: shouldBeCancelled};

console.log(example); // { isCancelled: false }

example.isCancelled = true;

console.log(example); // { isCancelled: true }
```

Whereas this does not:

```
let shouldBeCancelled = false;

const example = {isCancelled: shouldBeCancelled};

console.log(example); // { isCancelled: false }

shouldBeCancelled = true;

console.log(example); // { isCancelled: false }
```
