### ISSUE TITLE
Make content-disposition `inline` instead of `attachment`

### ISSUE THREAD

**Issue by canvaspixels** [upload-js/upload-js#4]
Please can you make `content-disposition` use `inline` instead of `attachment`?

I've noticed my images force-download when accessing them: with `inline` that won't be the case.

**Comment by ljwagerfield** [comment]
Great suggestion, thank you for raising!

This is now released in [`1.37.0`](https://github.com/upload-js/upload-js/releases/tag/v1.37.0).
